# Generated by Django 3.1.7 on 2021-03-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('code', models.TextField(max_length=10000)),
                ('approved', models.BooleanField(default=True)),
                ('date_approved', models.TextField()),
                ('language', models.IntegerField(choices=[(0, 'Javascript'), (1, 'Python')], default=0)),
                ('is_example', models.BooleanField(default=False)),
            ],
        ),
    ]
