# Generated by Django 3.1.7 on 2021-03-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
    ]
