# Generated by Django 3.1.7 on 2021-03-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0003_auto_20210315_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
