# Generated by Django 3.1.7 on 2021-03-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0004_auto_20210315_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
