# Generated by Django 3.1.7 on 2021-03-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0005_auto_20210315_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
