# Generated by Django 3.1.7 on 2021-05-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0006_auto_20210509_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='fadeout_time_milliseconds',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
