# Generated by Django 3.1.7 on 2021-05-12 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0007_code_duration_of_emulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='duration_of_emulation',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(8)]),
        ),
    ]
