# Generated by Django 3.1.7 on 2021-05-12 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0008_auto_20210512_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='duration_of_emulation',
            new_name='duration_of_emulation_in_seconds',
        ),
    ]
