# Generated by Django 3.1.7 on 2021-05-12 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0009_auto_20210512_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='priority',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
