0012_auto_20210512_2328# Generated by Django 3.1.7 on 2021-05-12 19:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0010_code_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='priority',
        ),
        migrations.CreateModel(
            name='PriorityQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codes.code')),
            ],
        ),
    ]
