# Generated by Django 3.1.7 on 2021-05-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0012_auto_20210512_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='generated_error',
            field=models.BooleanField(default=False),
        ),
    ]
