version: '3.8'

services:
  backend_test:
    build: ./backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.dev
    depends_on:
      - database_test
      - redis_test
  database_test:
    image: postgres:9.6.21-alpine
    env_file:
      - ./backend/.env.dev
  redis_test:
    image: redis:6.2.1-alpine
