version: '3.8'

services:
  backend:
    build: ./backend
    command: ["./wait-for-it.sh", "database:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.dev
    depends_on:
      - database
      - redis
  celery:
    build: ./backend
    command: celery -A lights worker -l INFO
    depends_on:
      - redis
      - database
  database:
    image: postgres:9.6.21-alpine
    env_file:
      - ./backend/.env.dev
  redis:
    image: redis:6.2.1-alpine