version: '3.8'

services:
  backend:
    build: ./backend:test
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.dev
    depends_on:
      - database
      - redis
  database:
    image: postgres:9.6.21-alpine:test
    env_file:
      - ./backend/.env.dev
  redis:
    image: redis:6.2.1-alpine:test
