name: CD

on:
  push:
    branches: 
      - $default-branch
      - development

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Create and start containers
        run: ls
      - name: Wait for containers to start
        run: pwd
