name: CI

on: [push]
  # push:
  #   branches: [ $default-branch ]
  # pull_request:
  #   branches: [ $default-branch ]

jobs:
  test:
    runs-on: tmaier/docker-compose:latest
    steps:
      - uses: actions/checkout@v2
      - name: Create and start containers
        run: docker-compose -f docker-compose.tests.yml up -d
      - name: Wait for containers to start
        run: sleep 15
      - name: Run database migrations on backend
        run: docker-compose exec -T backend python manage.py migrate
      - run: docker-compose exec -T backend pytest -p no:warnings --cov=. --cov-report html
      - run: docker-compose exec -T backend coverage report --precision=2
  # deploy:
  #   runs-on: tmaier/docker-compose:latest
  #   needs: [test]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Create and start containers
  #       run: docker-compose -f docker-compose.tests.yml up -d
